import type {
  AgentStatus,
  Attention,
  Bootstrap,
  RunProjection,
  ThreadProjection,
} from "../types";

export const agent: AgentStatus = {
  id: "agent-orbit",
  principalId: "principal-orbit",
  projectId: "project-sample",
  name: "Orbit",
  configRevision: 3,
  config: { model: "synthetic" },
  liveRunActivationCount: 1,
  liveAttentionActivationCount: 0,
  liveActivationCount: 1,
  nonterminalRunCount: 1,
  status: "active",
};

export const attention: Attention = {
  cursor: 1,
  id: "attention-1",
  projectId: "project-sample",
  channelId: "channel-general",
  threadRootId: "thread-1",
  messageRevisionId: "revision-1",
  targetAgentId: "agent-orbit",
  triggerKind: "AgentMention",
  status: "Open",
  revision: 1,
  handlerLeaseHolderPrincipalId: "principal-runtime",
  handlerLeaseExpiresAt: "2026-09-22T05:00:00.000Z",
  resolutionOutcome: null,
  resolvedRunId: null,
  createdAt: "2026-09-22T04:00:00.000Z",
  resolvedAt: null,
};

export const thread: ThreadProjection = {
  projectId: "project-sample",
  channelId: "channel-general",
  threadRootId: "thread-1",
  cursor: 2,
  messages: [
    {
      id: "thread-1",
      threadRootId: "thread-1",
      replyToMessageId: null,
      authorPrincipalId: "principal-human",
      authorAgentId: null,
      causedByAttentionId: null,
      causedByRunId: null,
      threadCursor: 1,
      latestRevision: 1,
      revisions: [
        {
          id: "revision-1",
          revision: 1,
          body: "Inspect the synthetic release path and report durable facts.",
          tombstone: false,
          targetAgentIds: ["agent-orbit"],
          createdAt: "2026-09-22T04:00:00.000Z",
        },
      ],
      targetAgentIds: ["agent-orbit"],
      createdAt: "2026-09-22T04:00:00.000Z",
    },
    {
      id: "message-2",
      threadRootId: "thread-1",
      replyToMessageId: "thread-1",
      authorPrincipalId: "principal-orbit",
      authorAgentId: "agent-orbit",
      causedByAttentionId: "attention-1",
      causedByRunId: "run-1",
      threadCursor: 2,
      latestRevision: 1,
      revisions: [
        {
          id: "revision-2",
          revision: 1,
          body: "The Run is active and the first input remains pending.",
          tombstone: false,
          targetAgentIds: [],
          createdAt: "2026-09-22T04:01:00.000Z",
        },
      ],
      targetAgentIds: [],
      createdAt: "2026-09-22T04:01:00.000Z",
    },
  ],
  attentions: [attention],
  runs: [
    {
      id: "run-1",
      projectId: "project-sample",
      homeChannelId: "channel-general",
      threadRootId: "thread-1",
      ownerAgentId: "agent-orbit",
      agentConfigRevision: 3,
      state: "Active",
      revision: 2,
      activationGeneration: 1,
      createdAt: "2026-09-22T04:01:00.000Z",
      updatedAt: "2026-09-22T04:02:00.000Z",
      terminalReason: null,
    },
  ],
  artifacts: [],
};

export const runProjection: RunProjection = {
  run: thread.runs[0]!,
  inputs: [
    {
      id: "run-input-1",
      runId: "run-1",
      messageRevisionId: "revision-1",
      sequence: 1,
      assignedByPrincipalId: "principal-orbit",
      assignedByActivationId: "activation-attention",
      sourceAttentionId: "attention-1",
      disposition: "Pending",
      dispositionRevision: 1,
      dispositionReason: null,
      supersededByRunInputId: null,
      createdAt: "2026-09-22T04:01:00.000Z",
    },
  ],
  activations: [
    {
      id: "activation-1",
      agentId: "agent-orbit",
      runId: "run-1",
      attentionId: null,
      configRevision: 3,
      runActivationGeneration: 1,
      runInputIds: ["run-input-1"],
      startedAt: "2026-09-22T04:01:00.000Z",
      expiresAt: "2026-09-22T05:01:00.000Z",
      revokedAt: null,
      revocationReason: null,
      finishedAt: null,
      outcome: null,
      detail: null,
    },
  ],
  providerAttempts: [
    {
      id: "provider-1",
      activationId: "activation-1",
      runId: "run-1",
      adapter: "synthetic-provider",
      adapterVersion: "1.0",
      capabilitySnapshot: { tools: [] },
      runInputIds: ["run-input-1"],
      requestIdempotencyKey: "provider-request-1",
      status: "Acknowledged",
      detail: null,
      startedAt: "2026-09-22T04:01:30.000Z",
      finishedAt: null,
    },
  ],
  activity: {
    items: [
      {
        id: "activity-1",
        runId: "run-1",
        activationId: "activation-1",
        providerAttemptId: "provider-1",
        sequence: 1,
        kind: "AgentOutput",
        payload: { text: "Inspecting the synthetic projection." },
        retentionClass: "durable",
        createdAt: "2026-09-22T04:02:00.000Z",
      },
    ],
    hasEarlier: false,
    earliestSequence: 1,
    latestSequence: 1,
  },
  artifacts: [],
};

export const bootstrap: Bootstrap = {
  project: { id: "project-sample", name: "Sample Project" },
  channels: [
    {
      id: "channel-general",
      projectId: "project-sample",
      name: "general",
    },
  ],
  agents: [agent],
  openAttentions: {
    items: [attention],
    nextCursor: null,
    hasMore: false,
    snapshotEventId: "event-7",
  },
  latestEventId: "event-7",
};
